target("imgui")
    set_kind("static")
    add_includedirs("include", "libs/imgui", "libs/imgui/backends", "libs/GLFW/include")
    add_files("libs/imgui/*.cpp", "libs/imgui/backends/imgui_impl_glfw.cpp", "libs/imgui/backends/imgui_impl_opengl3.cpp")

target("playground")
    set_kind("binary")
    set_languages("cxx20")
    add_includedirs("include", "../ijolib/include", "libs/imgui", "libs/imgui/backends", "libs/GLFW/include", "libs/ImGuiColorTextEdit")
    add_files("src/*.cpp", "libs/ImGuiColorTextEdit/TextEditor.cpp")
    add_deps("ijolib")
    add_deps("imgui")
    add_linkdirs("libs/GLFW/windows")
    add_links("glfw3dll", "opengl32", "gdi32", "shell32")