#include "common.h"
#include "chunk.h"
#include "log.h"
#include "ijoVM.h"

#if DEBUG
#include "debug.h"
#define LOG_LEVEL LOG_LEVEL_DEBUG
#endif

// Executes the generated byte codes
// Parameters:
//   - OP_CODE *code : List of OP_CODE to execute
//   - uint32_t size : The size of the OP_CODE list
void ExecuteCode(const OpCode *code, uint32_t size) {
}

int main(int argc, char **argv) {
  LogInfo("Creating a new ijoVM...");
  ijoVM *vm = ijoVMNew();

  
  Chunk chunk;
  ChunkNew(&chunk);

  int constant = ChunkAddConstant(&chunk, 1.2);
  ChunkWriteCode(&chunk, OP_MODULE, 1);
  ChunkWriteCode(&chunk, OP_CONSTANT, 3);
  ChunkWriteCode(&chunk, constant, 3);
  ChunkWriteCode(&chunk, OP_RETURN, 3);

#if DEBUG
  DisassembleChunk(&chunk, "Test Chunk");
#endif

  ChunkDelete(&chunk);

  LogInfo("Stopping the ijoVM");
  ijoVMDelete(vm);

  return 0;
}
